/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	zalandoorgv1 "github.com/zalando-incubator/es-operator/pkg/apis/zalando.org/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeElasticsearchMetricSets implements ElasticsearchMetricSetInterface
type FakeElasticsearchMetricSets struct {
	Fake *FakeZalandoV1
	ns   string
}

var elasticsearchmetricsetsResource = schema.GroupVersionResource{Group: "zalando.org", Version: "v1", Resource: "elasticsearchmetricsets"}

var elasticsearchmetricsetsKind = schema.GroupVersionKind{Group: "zalando.org", Version: "v1", Kind: "ElasticsearchMetricSet"}

// Get takes name of the elasticsearchMetricSet, and returns the corresponding elasticsearchMetricSet object, and an error if there is any.
func (c *FakeElasticsearchMetricSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *zalandoorgv1.ElasticsearchMetricSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(elasticsearchmetricsetsResource, c.ns, name), &zalandoorgv1.ElasticsearchMetricSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*zalandoorgv1.ElasticsearchMetricSet), err
}

// List takes label and field selectors, and returns the list of ElasticsearchMetricSets that match those selectors.
func (c *FakeElasticsearchMetricSets) List(ctx context.Context, opts v1.ListOptions) (result *zalandoorgv1.ElasticsearchMetricSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(elasticsearchmetricsetsResource, elasticsearchmetricsetsKind, c.ns, opts), &zalandoorgv1.ElasticsearchMetricSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &zalandoorgv1.ElasticsearchMetricSetList{ListMeta: obj.(*zalandoorgv1.ElasticsearchMetricSetList).ListMeta}
	for _, item := range obj.(*zalandoorgv1.ElasticsearchMetricSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested elasticsearchMetricSets.
func (c *FakeElasticsearchMetricSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(elasticsearchmetricsetsResource, c.ns, opts))

}

// Create takes the representation of a elasticsearchMetricSet and creates it.  Returns the server's representation of the elasticsearchMetricSet, and an error, if there is any.
func (c *FakeElasticsearchMetricSets) Create(ctx context.Context, elasticsearchMetricSet *zalandoorgv1.ElasticsearchMetricSet, opts v1.CreateOptions) (result *zalandoorgv1.ElasticsearchMetricSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(elasticsearchmetricsetsResource, c.ns, elasticsearchMetricSet), &zalandoorgv1.ElasticsearchMetricSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*zalandoorgv1.ElasticsearchMetricSet), err
}

// Update takes the representation of a elasticsearchMetricSet and updates it. Returns the server's representation of the elasticsearchMetricSet, and an error, if there is any.
func (c *FakeElasticsearchMetricSets) Update(ctx context.Context, elasticsearchMetricSet *zalandoorgv1.ElasticsearchMetricSet, opts v1.UpdateOptions) (result *zalandoorgv1.ElasticsearchMetricSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(elasticsearchmetricsetsResource, c.ns, elasticsearchMetricSet), &zalandoorgv1.ElasticsearchMetricSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*zalandoorgv1.ElasticsearchMetricSet), err
}

// Delete takes name of the elasticsearchMetricSet and deletes it. Returns an error if one occurs.
func (c *FakeElasticsearchMetricSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(elasticsearchmetricsetsResource, c.ns, name), &zalandoorgv1.ElasticsearchMetricSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeElasticsearchMetricSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(elasticsearchmetricsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &zalandoorgv1.ElasticsearchMetricSetList{})
	return err
}

// Patch applies the patch and returns the patched elasticsearchMetricSet.
func (c *FakeElasticsearchMetricSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *zalandoorgv1.ElasticsearchMetricSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(elasticsearchmetricsetsResource, c.ns, name, pt, data, subresources...), &zalandoorgv1.ElasticsearchMetricSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*zalandoorgv1.ElasticsearchMetricSet), err
}
