apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es9-master
spec:
  replicas: 1
  serviceName: es9-master
  selector:
    matchLabels:
      application: es9
      role: master
  template:
    metadata:
      labels:
        application: es9
        role: master
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: 1120Mi
            cpu: 100m
          limits:
            memory: 1120Mi
            cpu: 100m
        image: "docker.elastic.co/elasticsearch/elasticsearch:9.1.5"
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "ES_JAVA_OPTS"
          value: "-Xmx560m -Xms560m"
        - name: node.roles
          value: "master,data"
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: es9-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
