version: "2017-09-20"
allow_concurrent_pipelines: true
pipeline:
- id: build
  overlay: ci/golang
  cache:
    paths:
    - /go/pkg/mod       # pkg cache for Go modules
    - ~/.cache/go-build # Go build cache
  type: script
  commands:
  - desc: test
    cmd: |
      make test
  - desc: build
    cmd: |
      make build.docker
  - desc: push
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        IMAGE=registry-write.opensource.zalan.do/poirot/es-operator
        VERSION=$(git describe --tags --always --dirty)
      else
        IMAGE=registry-write.opensource.zalan.do/poirot/es-operator-test
        VERSION=$CDP_BUILD_VERSION
      fi
      IMAGE=$IMAGE VERSION=$VERSION make build.push
- id: e2e
  type: process
  desc: "E2E Tests"
  target: search-test
  process: microservice_standard_test
  debug_mode: true
  when:
    event: pull_request
  config:
    apply_manifests:
      env:
      - name: APPLICATION
        value: es-operator
      - name: DEPLOYMENT_PATH
        value: deploy/e2e
      - name: IMAGE
        value: "registry.opensource.zalan.do/poirot/es-operator-test:#{CDP_BUILD_VERSION}"
      - name: OPERATOR_ID
        value: "#{CDP_BUILD_VERSION}"
    end2end_tests:
      metadata:
        name: e2e
      spec:
        serviceAccountName: cdp
        restartPolicy: Never
        containers:
          - name: e2e
            image: "registry.opensource.zalan.do/poirot/es-operator-test-e2e:#{CDP_BUILD_VERSION}"
            command: ["/e2e"]
            env:
              - name: "OPERATOR_ID"
                value: "#{CDP_BUILD_VERSION}"
              - name: "E2E_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
