FROM registry.opensource.zalan.do/library/alpine-3.12:latest
MAINTAINER Team Lens @ Zalando SE <team-lens@zalando.de>

# add binary
ADD build/linux/e2e /

ENTRYPOINT ["/e2e", "-test.v", "-test.parallel", "64"]
