/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	zalandoorgv1 "github.com/zalando-incubator/es-operator/pkg/apis/zalando.org/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticsearchDataSetLister helps list ElasticsearchDataSets.
// All objects returned here must be treated as read-only.
type ElasticsearchDataSetLister interface {
	// List lists all ElasticsearchDataSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*zalandoorgv1.ElasticsearchDataSet, err error)
	// ElasticsearchDataSets returns an object that can list and get ElasticsearchDataSets.
	ElasticsearchDataSets(namespace string) ElasticsearchDataSetNamespaceLister
	ElasticsearchDataSetListerExpansion
}

// elasticsearchDataSetLister implements the ElasticsearchDataSetLister interface.
type elasticsearchDataSetLister struct {
	listers.ResourceIndexer[*zalandoorgv1.ElasticsearchDataSet]
}

// NewElasticsearchDataSetLister returns a new ElasticsearchDataSetLister.
func NewElasticsearchDataSetLister(indexer cache.Indexer) ElasticsearchDataSetLister {
	return &elasticsearchDataSetLister{listers.New[*zalandoorgv1.ElasticsearchDataSet](indexer, zalandoorgv1.Resource("elasticsearchdataset"))}
}

// ElasticsearchDataSets returns an object that can list and get ElasticsearchDataSets.
func (s *elasticsearchDataSetLister) ElasticsearchDataSets(namespace string) ElasticsearchDataSetNamespaceLister {
	return elasticsearchDataSetNamespaceLister{listers.NewNamespaced[*zalandoorgv1.ElasticsearchDataSet](s.ResourceIndexer, namespace)}
}

// ElasticsearchDataSetNamespaceLister helps list and get ElasticsearchDataSets.
// All objects returned here must be treated as read-only.
type ElasticsearchDataSetNamespaceLister interface {
	// List lists all ElasticsearchDataSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*zalandoorgv1.ElasticsearchDataSet, err error)
	// Get retrieves the ElasticsearchDataSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*zalandoorgv1.ElasticsearchDataSet, error)
	ElasticsearchDataSetNamespaceListerExpansion
}

// elasticsearchDataSetNamespaceLister implements the ElasticsearchDataSetNamespaceLister
// interface.
type elasticsearchDataSetNamespaceLister struct {
	listers.ResourceIndexer[*zalandoorgv1.ElasticsearchDataSet]
}
