/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/zalando-incubator/es-operator/pkg/apis/zalando.org/v1"
	scheme "github.com/zalando-incubator/es-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ElasticsearchDataSetsGetter has a method to return a ElasticsearchDataSetInterface.
// A group's client should implement this interface.
type ElasticsearchDataSetsGetter interface {
	ElasticsearchDataSets(namespace string) ElasticsearchDataSetInterface
}

// ElasticsearchDataSetInterface has methods to work with ElasticsearchDataSet resources.
type ElasticsearchDataSetInterface interface {
	Create(*v1.ElasticsearchDataSet) (*v1.ElasticsearchDataSet, error)
	Update(*v1.ElasticsearchDataSet) (*v1.ElasticsearchDataSet, error)
	UpdateStatus(*v1.ElasticsearchDataSet) (*v1.ElasticsearchDataSet, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ElasticsearchDataSet, error)
	List(opts metav1.ListOptions) (*v1.ElasticsearchDataSetList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ElasticsearchDataSet, err error)
	ElasticsearchDataSetExpansion
}

// elasticsearchDataSets implements ElasticsearchDataSetInterface
type elasticsearchDataSets struct {
	client rest.Interface
	ns     string
}

// newElasticsearchDataSets returns a ElasticsearchDataSets
func newElasticsearchDataSets(c *ZalandoV1Client, namespace string) *elasticsearchDataSets {
	return &elasticsearchDataSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the elasticsearchDataSet, and returns the corresponding elasticsearchDataSet object, and an error if there is any.
func (c *elasticsearchDataSets) Get(name string, options metav1.GetOptions) (result *v1.ElasticsearchDataSet, err error) {
	result = &v1.ElasticsearchDataSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ElasticsearchDataSets that match those selectors.
func (c *elasticsearchDataSets) List(opts metav1.ListOptions) (result *v1.ElasticsearchDataSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ElasticsearchDataSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested elasticsearchDataSets.
func (c *elasticsearchDataSets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a elasticsearchDataSet and creates it.  Returns the server's representation of the elasticsearchDataSet, and an error, if there is any.
func (c *elasticsearchDataSets) Create(elasticsearchDataSet *v1.ElasticsearchDataSet) (result *v1.ElasticsearchDataSet, err error) {
	result = &v1.ElasticsearchDataSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		Body(elasticsearchDataSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a elasticsearchDataSet and updates it. Returns the server's representation of the elasticsearchDataSet, and an error, if there is any.
func (c *elasticsearchDataSets) Update(elasticsearchDataSet *v1.ElasticsearchDataSet) (result *v1.ElasticsearchDataSet, err error) {
	result = &v1.ElasticsearchDataSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		Name(elasticsearchDataSet.Name).
		Body(elasticsearchDataSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *elasticsearchDataSets) UpdateStatus(elasticsearchDataSet *v1.ElasticsearchDataSet) (result *v1.ElasticsearchDataSet, err error) {
	result = &v1.ElasticsearchDataSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		Name(elasticsearchDataSet.Name).
		SubResource("status").
		Body(elasticsearchDataSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the elasticsearchDataSet and deletes it. Returns an error if one occurs.
func (c *elasticsearchDataSets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *elasticsearchDataSets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched elasticsearchDataSet.
func (c *elasticsearchDataSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ElasticsearchDataSet, err error) {
	result = &v1.ElasticsearchDataSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("elasticsearchdatasets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
