/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	zalandoorgv1 "github.com/zalando-incubator/es-operator/pkg/apis/zalando.org/v1"
	scheme "github.com/zalando-incubator/es-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ElasticsearchMetricSetsGetter has a method to return a ElasticsearchMetricSetInterface.
// A group's client should implement this interface.
type ElasticsearchMetricSetsGetter interface {
	ElasticsearchMetricSets(namespace string) ElasticsearchMetricSetInterface
}

// ElasticsearchMetricSetInterface has methods to work with ElasticsearchMetricSet resources.
type ElasticsearchMetricSetInterface interface {
	Create(ctx context.Context, elasticsearchMetricSet *zalandoorgv1.ElasticsearchMetricSet, opts metav1.CreateOptions) (*zalandoorgv1.ElasticsearchMetricSet, error)
	Update(ctx context.Context, elasticsearchMetricSet *zalandoorgv1.ElasticsearchMetricSet, opts metav1.UpdateOptions) (*zalandoorgv1.ElasticsearchMetricSet, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*zalandoorgv1.ElasticsearchMetricSet, error)
	List(ctx context.Context, opts metav1.ListOptions) (*zalandoorgv1.ElasticsearchMetricSetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *zalandoorgv1.ElasticsearchMetricSet, err error)
	ElasticsearchMetricSetExpansion
}

// elasticsearchMetricSets implements ElasticsearchMetricSetInterface
type elasticsearchMetricSets struct {
	*gentype.ClientWithList[*zalandoorgv1.ElasticsearchMetricSet, *zalandoorgv1.ElasticsearchMetricSetList]
}

// newElasticsearchMetricSets returns a ElasticsearchMetricSets
func newElasticsearchMetricSets(c *ZalandoV1Client, namespace string) *elasticsearchMetricSets {
	return &elasticsearchMetricSets{
		gentype.NewClientWithList[*zalandoorgv1.ElasticsearchMetricSet, *zalandoorgv1.ElasticsearchMetricSetList](
			"elasticsearchmetricsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *zalandoorgv1.ElasticsearchMetricSet { return &zalandoorgv1.ElasticsearchMetricSet{} },
			func() *zalandoorgv1.ElasticsearchMetricSetList { return &zalandoorgv1.ElasticsearchMetricSetList{} },
		),
	}
}
