/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/zalando-incubator/es-operator/pkg/apis/zalando.org/v1"
	scheme "github.com/zalando-incubator/es-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ElasticsearchMetricSetsGetter has a method to return a ElasticsearchMetricSetInterface.
// A group's client should implement this interface.
type ElasticsearchMetricSetsGetter interface {
	ElasticsearchMetricSets(namespace string) ElasticsearchMetricSetInterface
}

// ElasticsearchMetricSetInterface has methods to work with ElasticsearchMetricSet resources.
type ElasticsearchMetricSetInterface interface {
	Create(*v1.ElasticsearchMetricSet) (*v1.ElasticsearchMetricSet, error)
	Update(*v1.ElasticsearchMetricSet) (*v1.ElasticsearchMetricSet, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ElasticsearchMetricSet, error)
	List(opts metav1.ListOptions) (*v1.ElasticsearchMetricSetList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ElasticsearchMetricSet, err error)
	ElasticsearchMetricSetExpansion
}

// elasticsearchMetricSets implements ElasticsearchMetricSetInterface
type elasticsearchMetricSets struct {
	client rest.Interface
	ns     string
}

// newElasticsearchMetricSets returns a ElasticsearchMetricSets
func newElasticsearchMetricSets(c *ZalandoV1Client, namespace string) *elasticsearchMetricSets {
	return &elasticsearchMetricSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the elasticsearchMetricSet, and returns the corresponding elasticsearchMetricSet object, and an error if there is any.
func (c *elasticsearchMetricSets) Get(name string, options metav1.GetOptions) (result *v1.ElasticsearchMetricSet, err error) {
	result = &v1.ElasticsearchMetricSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ElasticsearchMetricSets that match those selectors.
func (c *elasticsearchMetricSets) List(opts metav1.ListOptions) (result *v1.ElasticsearchMetricSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ElasticsearchMetricSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested elasticsearchMetricSets.
func (c *elasticsearchMetricSets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a elasticsearchMetricSet and creates it.  Returns the server's representation of the elasticsearchMetricSet, and an error, if there is any.
func (c *elasticsearchMetricSets) Create(elasticsearchMetricSet *v1.ElasticsearchMetricSet) (result *v1.ElasticsearchMetricSet, err error) {
	result = &v1.ElasticsearchMetricSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		Body(elasticsearchMetricSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a elasticsearchMetricSet and updates it. Returns the server's representation of the elasticsearchMetricSet, and an error, if there is any.
func (c *elasticsearchMetricSets) Update(elasticsearchMetricSet *v1.ElasticsearchMetricSet) (result *v1.ElasticsearchMetricSet, err error) {
	result = &v1.ElasticsearchMetricSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		Name(elasticsearchMetricSet.Name).
		Body(elasticsearchMetricSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the elasticsearchMetricSet and deletes it. Returns an error if one occurs.
func (c *elasticsearchMetricSets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *elasticsearchMetricSets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched elasticsearchMetricSet.
func (c *elasticsearchMetricSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ElasticsearchMetricSet, err error) {
	result = &v1.ElasticsearchMetricSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("elasticsearchmetricsets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
