apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-operator
rules:
- apiGroups:
  - "zalando.org"
  resources:
  - elasticsearchdatasets
  - elasticsearchdatasets/status
  - elasticsearchmetricsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "zalando.org"
  resources:
  - elasticsearchmetricsets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: es-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: es-operator
subjects:
- kind: ServiceAccount
  name: es-operator
  namespace: es-operator-demo
