apiVersion: zalando.org/v1
kind: ElasticsearchDataSet
metadata:
  labels:
    application: elasticsearch
    role: data
    group: simple
  name: es-data-simple
  namespace: es-operator-demo
spec:
  replicas: 1
  hpaReplicas: 1
  scaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    minIndexReplicas: 0
    maxIndexReplicas: 3
    minShardsPerNode: 1
    maxShardsPerNode: 4
    scaleUpCPUBoundary: 90
    scaleUpThresholdDurationSeconds: 120
    scaleUpCooldownSeconds: 120
    scaleDownCPUBoundary: 80
    scaleDownThresholdDurationSeconds: 120
    scaleDownCooldownSeconds: 120
    diskUsagePercentScaledownWatermark: 90
  template:
    metadata:
      labels:
        application: elasticsearch
        role: data
        group: simple
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: elasticsearch
          env:
            - name: "node.name"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "node.attr.group"
              value: "simple"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xmx500m -Xms500m"
          image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0"
          ports:
            - containerPort: 9300
              name: transport
          readinessProbe:
            httpGet:
              path: /_cat/master
              port: 9200
            timeoutSeconds: 10
            initialDelaySeconds: 120
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      initContainers:
        - command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          image: busybox:1.30
          name: init-sysctl
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          securityContext:
            runAsUser: 0
            privileged: true
      volumes:
        - name: data
          emptyDir: { }
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
